# Generated by Django 5.1.5 on 2025-03-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_seller',
            field=models.CharField(choices=[('0', 'Client'), ('1', 'Vendeur'), ('2', 'Administrateur')], default='0', max_length=1),
        ),
    ]
