# Generated by Django 5.2 on 2025-05-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('seller_id', models.CharField(max_length=100)),
                ('delivery_man_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('en_attente', 'en attente'), ('attribue', 'attribué'), ('en_transi', 'en transit'), ('livres', 'livrés')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('transfert_vendeur', 'transfert vendeur'), ('enlevement_par_un_livreur', 'enlèvement par un livreur'), ('client_recu', 'client reçu')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='deliveries.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('demandee', 'demandée'), ('approuvee', 'approuvé'), ('rejetee', 'rejeté'), ('achevee', 'achevé')], default='demandee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery')),
            ],
        ),
    ]
